/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;
//important imports
import inventoryproject.C.CashierProcess;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import inventoryproject.C.Product;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.Arrays;
import java.io.IOException;
/**
 *
 * @author NEC
 */
public class Cashier extends javax.swing.JFrame {
        
    
    /** Creates new form Cashier */
    CashierProcess backBone = new CashierProcess(); //instantiate an object for the methods inside of this objects can be used
    //necessary variables
    long UPC = 0;
    long amount = 0;
    byte position = 0;
    double payment = 0;
    double total = 0;
    
    public Cashier(){
        initComponents();  
        centerWindow(this); //puts the window in the center
        setResizable(false);//disable user to resize window
        try{    //this will read the file that contains the products
            backBone.readFile();
             
        }catch(FileNotFoundException e){    //if something happens, it will dispose the frame and go back to the main menu casher
            JOptionPane.showMessageDialog(rootPane, "Inventory File not found!", "Alert", JOptionPane.WARNING_MESSAGE);
            dispose();
            MainMenuCashier back = new MainMenuCashier();
            back.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashierMain = new javax.swing.JPanel();
        cashierLbl = new javax.swing.JLabel();
        cashierLogo = new javax.swing.JLabel();
        cashierAddBtn1 = new javax.swing.JButton();
        cashierDeleteBtn1 = new javax.swing.JButton();
        cashierCheckoutBtn1 = new javax.swing.JButton();
        cashierUpdateBtn1 = new javax.swing.JButton();
        cashierTable = new javax.swing.JScrollPane();
        cashierTable1 = new javax.swing.JTable();
        totalValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cashierAdd = new javax.swing.JPanel();
        cashierAddLbl = new javax.swing.JLabel();
        cashierAddUPCTxtField = new javax.swing.JTextField();
        cashierAddUPCLbl = new javax.swing.JLabel();
        cashierAddBtn = new javax.swing.JButton();
        cashierAddUPCLbl1 = new javax.swing.JLabel();
        cashierAddAmountTxtField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cashierCheckOut = new javax.swing.JPanel();
        cashierCheckOutLbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cashierCheckoutTotalLbl = new javax.swing.JLabel();
        cashierCheckoutTotalTxtField = new javax.swing.JTextField();
        cashierCheckoutCashTxtField = new javax.swing.JTextField();
        cashierCheckoutCashLbl = new javax.swing.JLabel();
        cashierCheckOutConfirmBtn = new javax.swing.JButton();
        cashierCheckOutCancelBtn = new javax.swing.JButton();
        changeField = new javax.swing.JTextField();
        cashierCheckoutCashLbl1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cashierUpdate = new javax.swing.JPanel();
        cashierUpdateLbl = new javax.swing.JLabel();
        cashierUpdateUPCLbl = new javax.swing.JLabel();
        currentAmountField = new javax.swing.JTextField();
        newAmountField = new javax.swing.JTextField();
        cashierUpdateAmountLbl = new javax.swing.JLabel();
        cashierUpdateBtn = new javax.swing.JButton();
        productNameField = new javax.swing.JTextField();
        cashierUpdateUPCLbl1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Momentum - Cashier");
        setSize(new java.awt.Dimension(1098, 651));
        getContentPane().setLayout(new java.awt.CardLayout());

        cashierMain.setBackground(new java.awt.Color(223, 223, 223));
        cashierMain.setMinimumSize(new java.awt.Dimension(1098, 651));
        cashierMain.setPreferredSize(new java.awt.Dimension(1098, 651));
        cashierMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        cashierLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashierLbl.setText("Cashier");
        cashierMain.add(cashierLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 25));

        cashierLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/logo.png"))); // NOI18N
        cashierMain.add(cashierLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        cashierAddBtn1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cashierAddBtn1.setText("Add");
        cashierAddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierAddBtn1ActionPerformed(evt);
            }
        });
        cashierMain.add(cashierAddBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 106, 40));

        cashierDeleteBtn1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cashierDeleteBtn1.setText("Delete");
        cashierDeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierDeleteBtn1ActionPerformed(evt);
            }
        });
        cashierMain.add(cashierDeleteBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 106, 40));

        cashierCheckoutBtn1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cashierCheckoutBtn1.setText("Check Out");
        cashierCheckoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierCheckoutBtn1ActionPerformed(evt);
            }
        });
        cashierMain.add(cashierCheckoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 106, 40));

        cashierUpdateBtn1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cashierUpdateBtn1.setText("Update");
        cashierUpdateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierUpdateBtn1ActionPerformed(evt);
            }
        });
        cashierMain.add(cashierUpdateBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 106, 40));

        cashierTable1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Type", "Product Name", "Quantity", "Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cashierTable.setViewportView(cashierTable1);

        cashierMain.add(cashierTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 720, 430));

        totalValue.setEditable(false);
        totalValue.setBackground(new java.awt.Color(255, 255, 255));
        totalValue.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        totalValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalValue.setText("0");
        totalValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalValueActionPerformed(evt);
            }
        });
        cashierMain.add(totalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 189, 30));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL:");
        cashierMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/back button.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        cashierMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 103, 37, -1));
        cashierMain.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1100, 650));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/redCar.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        cashierMain.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 350, 730));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/tires bg.png"))); // NOI18N
        cashierMain.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 820, 650));

        getContentPane().add(cashierMain, "card2");

        cashierAdd.setBackground(new java.awt.Color(223, 223, 223));
        cashierAdd.setMinimumSize(new java.awt.Dimension(1098, 651));
        cashierAdd.setPreferredSize(new java.awt.Dimension(1098, 651));
        cashierAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierAddLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        cashierAddLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierAddLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashierAddLbl.setText("Add Product");
        cashierAdd.add(cashierAddLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, 25));

        cashierAddUPCTxtField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierAdd.add(cashierAddUPCTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 395, -1));

        cashierAddUPCLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierAddUPCLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierAddUPCLbl.setText("Enter UPC:");
        cashierAdd.add(cashierAddUPCLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        cashierAddBtn.setBackground(new java.awt.Color(189, 3, 2));
        cashierAddBtn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        cashierAddBtn.setText("Add");
        cashierAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierAddBtnActionPerformed(evt);
            }
        });
        cashierAdd.add(cashierAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 99, 37));

        cashierAddUPCLbl1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierAddUPCLbl1.setForeground(new java.awt.Color(255, 255, 255));
        cashierAddUPCLbl1.setText("Enter Amount:");
        cashierAdd.add(cashierAddUPCLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        cashierAddAmountTxtField1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierAdd.add(cashierAddAmountTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 395, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/back button.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        cashierAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 37, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/tires bg.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        cashierAdd.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        getContentPane().add(cashierAdd, "card3");

        cashierCheckOut.setBackground(new java.awt.Color(223, 223, 223));
        cashierCheckOut.setMinimumSize(new java.awt.Dimension(1098, 651));
        cashierCheckOut.setPreferredSize(new java.awt.Dimension(1098, 651));
        cashierCheckOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierCheckOutLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        cashierCheckOutLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckOutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashierCheckOutLbl.setText("Check Out");
        cashierCheckOut.add(cashierCheckOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 84, -1, 25));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/back button.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        cashierCheckOut.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        cashierCheckoutTotalLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckoutTotalLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckoutTotalLbl.setText("Total:");
        cashierCheckOut.add(cashierCheckoutTotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        cashierCheckoutTotalTxtField.setEditable(false);
        cashierCheckoutTotalTxtField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckoutTotalTxtField.setFocusable(false);
        cashierCheckoutTotalTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierCheckoutTotalTxtFieldActionPerformed(evt);
            }
        });
        cashierCheckOut.add(cashierCheckoutTotalTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 326, -1));

        cashierCheckoutCashTxtField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckoutCashTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierCheckoutCashTxtFieldActionPerformed(evt);
            }
        });
        cashierCheckOut.add(cashierCheckoutCashTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 287, 326, -1));

        cashierCheckoutCashLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckoutCashLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckoutCashLbl.setText("Cash:");
        cashierCheckOut.add(cashierCheckoutCashLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 290, -1, -1));

        cashierCheckOutConfirmBtn.setBackground(new java.awt.Color(189, 3, 2));
        cashierCheckOutConfirmBtn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckOutConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckOutConfirmBtn.setText("Confirm");
        cashierCheckOutConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierCheckOutConfirmBtnActionPerformed(evt);
            }
        });
        cashierCheckOut.add(cashierCheckOutConfirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 454, 99, 37));

        cashierCheckOutCancelBtn.setBackground(new java.awt.Color(102, 102, 102));
        cashierCheckOutCancelBtn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckOutCancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckOutCancelBtn.setText("Cancel");
        cashierCheckOutCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierCheckOutCancelBtnActionPerformed(evt);
            }
        });
        cashierCheckOut.add(cashierCheckOutCancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 454, 99, 37));

        changeField.setEditable(false);
        changeField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        changeField.setFocusable(false);
        changeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFieldActionPerformed(evt);
            }
        });
        cashierCheckOut.add(changeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 326, -1));

        cashierCheckoutCashLbl1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierCheckoutCashLbl1.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckoutCashLbl1.setText("Change:");
        cashierCheckOut.add(cashierCheckoutCashLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/tires bg.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        cashierCheckOut.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(cashierCheckOut, "card4");

        cashierUpdate.setBackground(new java.awt.Color(223, 223, 223));
        cashierUpdate.setMinimumSize(new java.awt.Dimension(1098, 651));
        cashierUpdate.setPreferredSize(new java.awt.Dimension(1098, 651));
        cashierUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cashierUpdateLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        cashierUpdateLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierUpdateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashierUpdateLbl.setText("Update Product");
        cashierUpdate.add(cashierUpdateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 25));

        cashierUpdateUPCLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierUpdateUPCLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierUpdateUPCLbl.setText("Current Amount:");
        cashierUpdate.add(cashierUpdateUPCLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        currentAmountField.setEditable(false);
        currentAmountField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        currentAmountField.setFocusable(false);
        cashierUpdate.add(currentAmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 326, -1));

        newAmountField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        newAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAmountFieldActionPerformed(evt);
            }
        });
        cashierUpdate.add(newAmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 326, -1));

        cashierUpdateAmountLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierUpdateAmountLbl.setForeground(new java.awt.Color(255, 255, 255));
        cashierUpdateAmountLbl.setText("Enter New Amount:");
        cashierUpdate.add(cashierUpdateAmountLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        cashierUpdateBtn.setBackground(new java.awt.Color(189, 3, 2));
        cashierUpdateBtn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        cashierUpdateBtn.setText("Update");
        cashierUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierUpdateBtnActionPerformed(evt);
            }
        });
        cashierUpdate.add(cashierUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 99, 37));

        productNameField.setEditable(false);
        productNameField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        productNameField.setFocusable(false);
        cashierUpdate.add(productNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 326, -1));

        cashierUpdateUPCLbl1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cashierUpdateUPCLbl1.setForeground(new java.awt.Color(255, 255, 255));
        cashierUpdateUPCLbl1.setText("Product Name:");
        cashierUpdate.add(cashierUpdateUPCLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/back button.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        cashierUpdate.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 32, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/tires bg.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        cashierUpdate.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        getContentPane().add(cashierUpdate, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // this is for adding the product in the order list
    private void cashierAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierAddBtnActionPerformed
        try{
            UPC = Long.parseLong(cashierAddUPCTxtField.getText());  //gets the text in the textfield for the adding of the product in the order list
            amount = Long.parseLong(cashierAddAmountTxtField1.getText());
            
            if(amount > 0){ //chacks if the amount entered is valid
                if(!checkExisting(UPC)){    //checks if there is a same existing product in the list
                    backBone.add(UPC, amount);  //perform add in the orderlist
                    setTables();    //set the table for the new product
                }
                cashierAdd.setVisible(false);   //goes back to the main panel of the cashier system
                cashierMain.setVisible(true);
                cashierAddUPCTxtField.setText("");  //sets the text to blank
                cashierAddAmountTxtField1.setText("");
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid amount input!", "Warning", JOptionPane.WARNING_MESSAGE);
        }catch (NumberFormatException e){   //this will catch the invalid input
            JOptionPane.showMessageDialog(null, "Invalid Input Format!", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cashierAddBtnActionPerformed

    //checks if there is a same existing product in the order list
    private boolean checkExisting(long UPC){    //returns true if there is an identical product
        for(Product product: backBone.order){   //iterate in order to see if there is a same existing product in the list
            if(product.getUniversalProductKey() == UPC){    //prompts the user if there is an identical product
                JOptionPane.showMessageDialog(rootPane, "Product already exist in the list!", "Alert", JOptionPane.WARNING_MESSAGE);
                return true;
            }
        }
        return false;
    }
    
    //set the ordered products in the table
    private void setTables(){
        DefaultTableModel model = (DefaultTableModel) cashierTable1.getModel(); //get the model of the table and set its row to zero
        model.setRowCount(0);
        double total = 0;   //resets the total to 0
        for(Product c: backBone.order){ //iterate and add the product in the table
            String[] toBeAdded = {c.getBrandName(), c.getType(), c.getName(), "" + c.getAmount(), "" + c.getPrice() , "" + c.getPrice() * c.getAmount()};
            model.addRow(toBeAdded);
            total += c.getPrice() * c.getAmount();
        }     
        totalValue.setText("" + total); //sets the text field to blank
    }
    
    //checks out the ordered products in the ordered list
    private void cashierCheckOutConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckOutConfirmBtnActionPerformed
        total = Double.parseDouble(totalValue.getText());   //get the total cost of the product
        try{
            payment = Double.parseDouble(cashierCheckoutCashTxtField.getText());    //gets the payment received from the user
            if(payment < total) //checks if the payment is sufficient
                JOptionPane.showMessageDialog(rootPane, "Payment insufficient!", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                Receipt receipt = new Receipt(backBone.order, payment); //instantiate a receipt object that will print the receipt of the current transactions
                receipt.setVisible(true);
                changeField.setText((payment - Double.parseDouble(totalValue.getText())) + "");
                cashierCheckOutConfirmBtn.setVisible(false); //for the added effects
                cashierCheckOutCancelBtn.setVisible(false);
                cashierCheckoutCashTxtField.setEditable(false);
                cashierCheckoutCashTxtField.setFocusable(false);
                receipt.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //so that the program will not terminate even if the frame of the receip is clicked on X
                backBone.recordTransaction(total, payment); //records the transaction
                backBone.saveChanges(); //save the changes in the product's stocks
                setTables();
            }
        }catch(IOException e){  //if there is a problem encountered
            JOptionPane.showMessageDialog(rootPane, "An error has occured!", "Alert", JOptionPane.ERROR_MESSAGE);
            cashierCheckOut.setVisible(false);
            cashierMain.setVisible(true);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Invalid Input Format!", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cashierCheckOutConfirmBtnActionPerformed

    
    //if the checkout is cancelled
    private void cashierCheckOutCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckOutCancelBtnActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Operation has been cancelled!", "", JOptionPane.INFORMATION_MESSAGE);
        cashierCheckOut.setVisible(false);      //Goes back to the cashier main panel
        cashierMain.setVisible(true);
    }//GEN-LAST:event_cashierCheckOutCancelBtnActionPerformed

    //for updating product's amount in the list
    private void cashierUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierUpdateBtnActionPerformed
        try{
            amount = Long.parseLong(newAmountField.getText());  //gets amount input
            if(amount >= 0){    //if the amount is greater than zero
                if(backBone.change(position, amount))   //perform update process
                    setTables();    //sets table
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Invalid Input amount!", "Warning", JOptionPane.ERROR_MESSAGE);
            cashierUpdate.setVisible(false); //goes back to the cashier main panel
            cashierMain.setVisible(true);   
            newAmountField.setText(""); //sets =the amount field to blank
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Invalid Input Format!", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cashierUpdateBtnActionPerformed

    //for adding the products in the ordered list
    private void cashierAddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierAddBtn1ActionPerformed
        cashierMain.setVisible(false);  //goes to add panel
        cashierAdd.setVisible(true);
    }//GEN-LAST:event_cashierAddBtn1ActionPerformed

    //for exiting in the cashier and going to the main menu cashier
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();  //disposes the frame
        backBone.products.clear();  //clear the contents of the arraylist of hashtable
        MainMenuCashier back = new MainMenuCashier();   //intantiate the object of the main menu cashier
        back.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void totalValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalValueActionPerformed
    }//GEN-LAST:event_totalValueActionPerformed

    //this is for reversing the array of the selected items in the ordered list
    private void reverseArray(int[] array){
        for(int i = 0; i < array.length / 2; i++){  //reverses the array
            int temp = array[i];
            array[i] = array[array.length - i - 1];
            array[array.length - i - 1] = temp;
        }
    }
    
    //deletes the selected items in the ordered list
    private void cashierDeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierDeleteBtn1ActionPerformed
        int[] selectedIndex = cashierTable1.getSelectedRows();  //gets the selected 
        if(selectedIndex.length > 0){   //checks if the user selected a product in the ordered list
            Arrays.sort(selectedIndex, 0, selectedIndex.length);    //sorts the list of the selected index in the ordered products
            reverseArray(selectedIndex);    //reverse the array for the proper deletion
            if(JOptionPane.showConfirmDialog(null, "Contnue?", "Confirmation", JOptionPane.OK_CANCEL_OPTION) == 0){
                for(int c: selectedIndex)   //perform deletion
                    backBone.delete(c);
                setTables();    //sets the values of the table
            }
            else
                JOptionPane.showMessageDialog(null, "Operation has been cancelled!");
        }
        else
            JOptionPane.showMessageDialog(null, "Please select a product!", "Warning", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_cashierDeleteBtn1ActionPerformed

    //for the update of the cashier
    private void cashierUpdateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierUpdateBtn1ActionPerformed
        int[] selectedIndex = cashierTable1.getSelectedRows();  //gets the selected index of the ordered products in the table
        if(selectedIndex.length == 0)   //if the user does not select a product in the list
            JOptionPane.showMessageDialog(rootPane, "Please select a product!", "Warning", JOptionPane.ERROR_MESSAGE);
        else if(selectedIndex.length > 1)   //if the user has selected more than one product in the ordered list table 
            JOptionPane.showMessageDialog(rootPane, "Please select only one product!", "Warning", JOptionPane.ERROR_MESSAGE);
        else{
            productNameField.setText(backBone.order.get(selectedIndex[0]).getName());   //sets the name and the amount that is in orderd list
            currentAmountField.setText("" + backBone.order.get(selectedIndex[0]).getAmount());
            cashierMain.setVisible(false);  //goes to the update panel in the cashier
            cashierUpdate.setVisible(true);
        }
    }//GEN-LAST:event_cashierUpdateBtn1ActionPerformed

    private void newAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAmountFieldActionPerformed
    }//GEN-LAST:event_newAmountFieldActionPerformed

    //when the user clicks the checkout button in the cashier
    private void cashierCheckoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckoutBtn1ActionPerformed
        if(backBone.order.isEmpty())    //if the user does not order a product in the cashier
            JOptionPane.showMessageDialog(null, "Please order a product!", "Warning", JOptionPane.ERROR_MESSAGE);
        else{   //perform checkout
            cashierCheckoutTotalTxtField.setText(totalValue.getText());
            cashierCheckoutCashTxtField.setText("");
            cashierMain.setVisible(false);  //goes to the check out panel
            cashierCheckOut.setVisible(true);
        }
    }//GEN-LAST:event_cashierCheckoutBtn1ActionPerformed

    private void cashierCheckoutCashTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckoutCashTxtFieldActionPerformed
    }//GEN-LAST:event_cashierCheckoutCashTxtFieldActionPerformed

    private void cashierCheckoutTotalTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierCheckoutTotalTxtFieldActionPerformed
    }//GEN-LAST:event_cashierCheckoutTotalTxtFieldActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        newAmountField.setText("");
        cashierUpdate.setVisible(false);  //goes to the update panel
        cashierMain.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        cashierAddAmountTxtField1.setText("");
        cashierAddUPCTxtField.setText("");
        cashierAdd.setVisible(false);
        cashierMain.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        cashierCheckOut.setVisible(false);  //go back to main panel of the cashier
        cashierCheckOutCancelBtn.setVisible(true);
        cashierCheckOutConfirmBtn.setVisible(true);
        cashierCheckoutCashTxtField.setEditable(true);
        cashierCheckoutCashTxtField.setFocusable(true);
        changeField.setText("");
        cashierMain.setVisible(true);
        cashierCheckoutCashTxtField.setText("");    //sets the cashi input textfield to blank
    }//GEN-LAST:event_jLabel17MouseClicked

    private void changeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeFieldActionPerformed

   //for centering the the window
    private void centerWindow(Window w)
    {
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    setLocation((d.width-w.getWidth())/2,
    (d.height-w.getHeight())/2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cashierAdd;
    private javax.swing.JTextField cashierAddAmountTxtField1;
    private javax.swing.JButton cashierAddBtn;
    private javax.swing.JButton cashierAddBtn1;
    private javax.swing.JLabel cashierAddLbl;
    private javax.swing.JLabel cashierAddUPCLbl;
    private javax.swing.JLabel cashierAddUPCLbl1;
    private javax.swing.JTextField cashierAddUPCTxtField;
    private javax.swing.JPanel cashierCheckOut;
    private javax.swing.JButton cashierCheckOutCancelBtn;
    private javax.swing.JButton cashierCheckOutConfirmBtn;
    private javax.swing.JLabel cashierCheckOutLbl;
    private javax.swing.JButton cashierCheckoutBtn1;
    private javax.swing.JLabel cashierCheckoutCashLbl;
    private javax.swing.JLabel cashierCheckoutCashLbl1;
    private javax.swing.JTextField cashierCheckoutCashTxtField;
    private javax.swing.JLabel cashierCheckoutTotalLbl;
    private javax.swing.JTextField cashierCheckoutTotalTxtField;
    private javax.swing.JButton cashierDeleteBtn1;
    private javax.swing.JLabel cashierLbl;
    private javax.swing.JLabel cashierLogo;
    private javax.swing.JPanel cashierMain;
    private javax.swing.JScrollPane cashierTable;
    private javax.swing.JTable cashierTable1;
    private javax.swing.JPanel cashierUpdate;
    private javax.swing.JLabel cashierUpdateAmountLbl;
    private javax.swing.JButton cashierUpdateBtn;
    private javax.swing.JButton cashierUpdateBtn1;
    private javax.swing.JLabel cashierUpdateLbl;
    private javax.swing.JLabel cashierUpdateUPCLbl;
    private javax.swing.JLabel cashierUpdateUPCLbl1;
    private javax.swing.JTextField changeField;
    private javax.swing.JTextField currentAmountField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField newAmountField;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField totalValue;
    // End of variables declaration//GEN-END:variables

}
