/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author NEC
 */
public class Loading extends javax.swing.JFrame {
    
    public Loading() {
        initComponents();
        centerWindow(this); //puts the window in the center
        setResizable(false);//disable user to resize window
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        progressPercentage = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOADING");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, 30));

        progressLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        progressLabel.setForeground(new java.awt.Color(255, 255, 255));
        progressLabel.setText("Please wait...");
        jPanel1.add(progressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        progressPercentage.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        progressPercentage.setForeground(new java.awt.Color(255, 255, 255));
        progressPercentage.setText("0%");
        jPanel1.add(progressPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, 20));

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(189, 3, 2));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 400, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/Loading_Gif.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/Loading_BG.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void simulateProgress() {
        try {
            for (int i = 0; i <= 100; i++) {
                final int progressValue = i; // Declare as final

                Thread.sleep(100);
                SwingUtilities.invokeLater(() -> {
                    progressPercentage.setText(progressValue + "%");
                    if (progressValue == 10) {
                        progressLabel.setText("Loading the latest and greatest automotive essentials for you... ");
                    }
                    if (progressValue == 20) {
                        progressLabel.setText("Buffering repair resources... Your patience is our horsepower.");
                    }
                    if (progressValue == 50) {
                        progressLabel.setText("Scanning for upgrades... Your car's next improvement is on its way.");
                    } 
                    if (progressValue == 80) {
                        progressLabel.setText("Loading toolkit... Every mechanic needs the right tools.");
                    } 
                    if (progressValue == 90) {
                        progressLabel.setText("Spinning the wheel of progress... Almost there.");
                    } 
                    if (progressValue == 100) {
                        progressLabel.setText("Assembling the finest components for your automotive dreams...");
                    }                     
                    // Add similar blocks for other conditions
                    jProgressBar1.setValue(progressValue);
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public static void main(String args[]) {
        Loading sp = new Loading();
        sp.setVisible(true);
        sp.simulateProgress();
    }
    
    private void centerWindow(Window w)
    {
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    setLocation((d.width-w.getWidth())/2,
    (d.height-w.getHeight())/2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JLabel progressPercentage;
    // End of variables declaration//GEN-END:variables
}
