/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;
//necessary imports
import inventoryproject.C.LogInProcess;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NEC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        centerWindow(this); //puts the window in the center
        setResizable(false);//disable user to resize window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginCashierRadioBtn = new javax.swing.JRadioButton();
        loginAdminRadioBtn = new javax.swing.JRadioButton();
        loginPasswordTxtField = new javax.swing.JPasswordField();
        loginPasswordLbl = new javax.swing.JLabel();
        loginNameTextField = new javax.swing.JTextField();
        loginUsernameLbl = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        loginSaveBtn = new javax.swing.JButton();
        loginDontHaveAccLbl = new javax.swing.JLabel();
        loginSignUpLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Momentum - Login");
        setSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(121, 121, 121));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1098, 651));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(171, 171, 171));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 171, 171), 1, true));

        BGroup.add(loginCashierRadioBtn);
        loginCashierRadioBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loginCashierRadioBtn.setForeground(new java.awt.Color(25, 25, 25));
        loginCashierRadioBtn.setText("Cashier");

        BGroup.add(loginAdminRadioBtn);
        loginAdminRadioBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loginAdminRadioBtn.setForeground(new java.awt.Color(25, 25, 25));
        loginAdminRadioBtn.setText("Admin");

        loginPasswordTxtField.setBackground(new java.awt.Color(223, 223, 223));
        loginPasswordTxtField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loginPasswordTxtField.setForeground(new java.awt.Color(32, 32, 32));

        loginPasswordLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loginPasswordLbl.setForeground(new java.awt.Color(25, 25, 25));
        loginPasswordLbl.setText("Password");

        loginNameTextField.setBackground(new java.awt.Color(223, 223, 223));
        loginNameTextField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loginNameTextField.setForeground(new java.awt.Color(32, 32, 32));

        loginUsernameLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loginUsernameLbl.setForeground(new java.awt.Color(25, 25, 25));
        loginUsernameLbl.setText("Username");

        loginLabel.setBackground(new java.awt.Color(79, 78, 78));
        loginLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(25, 25, 25));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        loginSaveBtn.setBackground(new java.awt.Color(189, 3, 2));
        loginSaveBtn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        loginSaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginSaveBtn.setText("Login");
        loginSaveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSaveBtnActionPerformed(evt);
            }
        });

        loginDontHaveAccLbl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loginDontHaveAccLbl.setForeground(new java.awt.Color(25, 25, 25));
        loginDontHaveAccLbl.setText("Don’t have an account?");

        loginSignUpLbl.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        loginSignUpLbl.setForeground(new java.awt.Color(25, 25, 25));
        loginSignUpLbl.setText("Sign Up Now");
        loginSignUpLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginSignUpLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginSignUpLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(loginAdminRadioBtn)
                .addGap(48, 48, 48)
                .addComponent(loginCashierRadioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginUsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordLbl))
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(loginDontHaveAccLbl)
                            .addGap(7, 7, 7)
                            .addComponent(loginSignUpLbl)))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(loginSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(124, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(loginUsernameLbl)
                .addGap(8, 8, 8)
                .addComponent(loginNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(loginPasswordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginPasswordLbl))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginAdminRadioBtn)
                    .addComponent(loginCashierRadioBtn))
                .addGap(255, 255, 255))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginLabel)
                    .addGap(403, 403, 403)
                    .addComponent(loginSaveBtn)
                    .addGap(21, 21, 21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginDontHaveAccLbl)
                        .addComponent(loginSignUpLbl))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 380, 580));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/logo white.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Momentum");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/car.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/bg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //log in 
    private void loginSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSaveBtnActionPerformed
        try{
            String userName = loginNameTextField.getText(); //get the user input
            String password = String.valueOf(loginPasswordTxtField.getPassword());
                
            if(!userName.equals("") && !password.equals("")){   //if not blank
                if(loginAdminRadioBtn.isSelected()){    //log in base on the position selected
                    if(new LogInProcess().logInPanel(userName, password, false)){   //if the username and password matches to an existing account
                        dispose();  //dispose the fram and go to main menu admin frame
                        MainMenuAdmin mainMenuAdmin = new MainMenuAdmin();
                        mainMenuAdmin.setVisible(true);
                        
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Wrong Username or Password!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else if(loginCashierRadioBtn.isSelected()){ //log in base on the position selected
                    if(new LogInProcess().logInPanel(userName, password, true)){    //if the username and password matches to an existing account
                        dispose();
                        MainMenuCashier cashier = new MainMenuCashier();
                        cashier.setVisible(true);
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Wrong Username or Password!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(rootPane, "Please Select Cashier of Admin", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Please fill up the following", "Warning", JOptionPane.WARNING_MESSAGE);
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "An Error has occured!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loginSaveBtnActionPerformed

    //delivers the user to the sign up frame
    private void loginSignUpLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginSignUpLblMouseClicked
        dispose();  //dispose the frame and goes to sign up frame
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
    }//GEN-LAST:event_loginSignUpLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    private void centerWindow(Window w)
    {
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    setLocation((d.width-w.getWidth())/2,
    (d.height-w.getHeight())/2);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton loginAdminRadioBtn;
    private javax.swing.JRadioButton loginCashierRadioBtn;
    private javax.swing.JLabel loginDontHaveAccLbl;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginNameTextField;
    private javax.swing.JLabel loginPasswordLbl;
    private javax.swing.JPasswordField loginPasswordTxtField;
    private javax.swing.JButton loginSaveBtn;
    private javax.swing.JLabel loginSignUpLbl;
    private javax.swing.JLabel loginUsernameLbl;
    // End of variables declaration//GEN-END:variables
}
