/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

/**
 *
 * @author NEC
 */
public class MainMenuCashier extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuCashier
     */
    public MainMenuCashier() {
        initComponents();
        centerWindow(this); //puts the window in the center
        setResizable(false);//disable user to resize window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        menuLbl = new javax.swing.JLabel();
        menuCashierExitBtn = new javax.swing.JButton();
        menuCashierBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Momentum - Menu");

        jPanel2.setBackground(new java.awt.Color(121, 121, 121));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        menuLbl.setForeground(new java.awt.Color(255, 255, 255));
        menuLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLbl.setText("MENU");
        jPanel2.add(menuLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 173, 22));

        menuCashierExitBtn.setBackground(new java.awt.Color(189, 3, 2));
        menuCashierExitBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuCashierExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuCashierExitBtn.setText("Exit");
        menuCashierExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        menuCashierExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCashierExitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(menuCashierExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 173, 30));

        menuCashierBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuCashierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/manage account.png"))); // NOI18N
        menuCashierBtn.setText("Cashier");
        menuCashierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCashierBtnActionPerformed(evt);
            }
        });
        jPanel2.add(menuCashierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 173, 46));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/redWallpaperrr.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 420, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/bg.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //go to login 
    private void menuCashierExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCashierExitBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_menuCashierExitBtnActionPerformed

    //go to the cashier
    private void menuCashierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCashierBtnActionPerformed
        dispose();
        Cashier cashier = new Cashier();
        cashier.setVisible(true);
    }//GEN-LAST:event_menuCashierBtnActionPerformed
    //for centering the the window
    private void centerWindow(Window w)
    {
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    setLocation((d.width-w.getWidth())/2,
    (d.height-w.getHeight())/2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menuCashierBtn;
    private javax.swing.JButton menuCashierExitBtn;
    private javax.swing.JLabel menuLbl;
    // End of variables declaration//GEN-END:variables
}
