/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

/**
 *
 * @author NEC
 */
public class MainMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuAdmin
     */
    public MainMenuAdmin() {
        initComponents();
        centerWindow(this); //puts the window in the center
        setResizable(false);//disable user to resize window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuAdminInventoryBtn = new javax.swing.JButton();
        menuAdminExitBtn = new javax.swing.JButton();
        menuAdminLbl = new javax.swing.JLabel();
        menuAdminManageAccBtn = new javax.swing.JButton();
        menuAdminTransactionBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Momentum - Menu");

        jPanel1.setPreferredSize(new java.awt.Dimension(1098, 651));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuAdminInventoryBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuAdminInventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/inventory.png"))); // NOI18N
        menuAdminInventoryBtn.setText("Inventory               ");
        menuAdminInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminInventoryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(menuAdminInventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, -1));

        menuAdminExitBtn.setBackground(new java.awt.Color(189, 3, 2));
        menuAdminExitBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuAdminExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuAdminExitBtn.setText("Exit");
        menuAdminExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        menuAdminExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminExitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(menuAdminExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 173, 34));

        menuAdminLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        menuAdminLbl.setForeground(new java.awt.Color(255, 255, 255));
        menuAdminLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuAdminLbl.setText("MENU");
        jPanel1.add(menuAdminLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 173, 22));

        menuAdminManageAccBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuAdminManageAccBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/manage account.png"))); // NOI18N
        menuAdminManageAccBtn.setText("Manage Account");
        menuAdminManageAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminManageAccBtnActionPerformed(evt);
            }
        });
        jPanel1.add(menuAdminManageAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 170, -1));

        menuAdminTransactionBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        menuAdminTransactionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/transaction.png"))); // NOI18N
        menuAdminTransactionBtn.setText("Transaction          ");
        menuAdminTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminTransactionBtnActionPerformed(evt);
            }
        });
        jPanel1.add(menuAdminTransactionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/redWallpaperrr.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 420, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/bg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //for centering the the window
    private void centerWindow(Window w)
    {
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    setLocation((d.width-w.getWidth())/2,
    (d.height-w.getHeight())/2);
    }

    //go to inventory
    private void menuAdminInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminInventoryBtnActionPerformed
        dispose();
        Inventory inventory = new Inventory();
        inventory.setVisible(true);
    }//GEN-LAST:event_menuAdminInventoryBtnActionPerformed

    //go to login
    private void menuAdminExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminExitBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_menuAdminExitBtnActionPerformed

    //go to account management
    private void menuAdminManageAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminManageAccBtnActionPerformed
        dispose();
        AccountManager manage_account = new AccountManager();
        manage_account.setVisible(true);
    }//GEN-LAST:event_menuAdminManageAccBtnActionPerformed

    //go to transaction records
    private void menuAdminTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminTransactionBtnActionPerformed
        dispose();
        Transaction transactions = new Transaction();
        transactions.setVisible(true);
        transactions.setResizable(false);
    }//GEN-LAST:event_menuAdminTransactionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menuAdminExitBtn;
    private javax.swing.JButton menuAdminInventoryBtn;
    private javax.swing.JLabel menuAdminLbl;
    private javax.swing.JButton menuAdminManageAccBtn;
    private javax.swing.JButton menuAdminTransactionBtn;
    // End of variables declaration//GEN-END:variables
}
