/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryproject;
import inventoryproject.C.AccountManagerProcess;
import inventoryproject.Login;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JOptionPane;
import java.io.IOException;


/**
 *
 * @author NEC
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        centerWindow(this); //puts the window in the center
        setResizable(false);//disable user to resize window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        signUpRegisterLbl = new javax.swing.JLabel();
        signUpUsernameLbl = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        signUpPasswordLbl = new javax.swing.JLabel();
        signUpPasswordTextField = new javax.swing.JPasswordField();
        signUpConfirmPasswordLbl = new javax.swing.JLabel();
        signUpConfirmPasswordTextField = new javax.swing.JPasswordField();
        signUpUsernameLbl1 = new javax.swing.JLabel();
        signInKeyTextField = new javax.swing.JPasswordField();
        loginAdminRadioBtn = new javax.swing.JRadioButton();
        loginCashierRadioBtn = new javax.swing.JRadioButton();
        signUpBtn = new javax.swing.JButton();
        signUpLoginLbl = new javax.swing.JLabel();
        signUpHaveAccLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Momentum - Sign Up");

        jPanel1.setBackground(new java.awt.Color(121, 121, 121));
        jPanel1.setPreferredSize(new java.awt.Dimension(1098, 651));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(171, 171, 171));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 171, 171), 1, true));

        signUpRegisterLbl.setBackground(new java.awt.Color(79, 78, 78));
        signUpRegisterLbl.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        signUpRegisterLbl.setForeground(new java.awt.Color(25, 25, 25));
        signUpRegisterLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpRegisterLbl.setText("Register");

        signUpUsernameLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpUsernameLbl.setForeground(new java.awt.Color(25, 25, 25));
        signUpUsernameLbl.setText("Username");

        usernameTextField.setBackground(new java.awt.Color(223, 223, 223));
        usernameTextField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(32, 32, 32));

        signUpPasswordLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpPasswordLbl.setForeground(new java.awt.Color(25, 25, 25));
        signUpPasswordLbl.setText("Password");

        signUpPasswordTextField.setBackground(new java.awt.Color(223, 223, 223));
        signUpPasswordTextField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpPasswordTextField.setForeground(new java.awt.Color(32, 32, 32));

        signUpConfirmPasswordLbl.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpConfirmPasswordLbl.setForeground(new java.awt.Color(25, 25, 25));
        signUpConfirmPasswordLbl.setText("Confirm Password");

        signUpConfirmPasswordTextField.setBackground(new java.awt.Color(223, 223, 223));
        signUpConfirmPasswordTextField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpConfirmPasswordTextField.setForeground(new java.awt.Color(32, 32, 32));

        signUpUsernameLbl1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpUsernameLbl1.setForeground(new java.awt.Color(25, 25, 25));
        signUpUsernameLbl1.setText("Sign In Key");

        signInKeyTextField.setBackground(new java.awt.Color(223, 223, 223));
        signInKeyTextField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signInKeyTextField.setForeground(new java.awt.Color(32, 32, 32));

        loginAdminRadioBtn.setBackground(new java.awt.Color(171, 171, 171));
        BGroup2.add(loginAdminRadioBtn);
        loginAdminRadioBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loginAdminRadioBtn.setForeground(new java.awt.Color(25, 25, 25));
        loginAdminRadioBtn.setText("Admin");

        loginCashierRadioBtn.setBackground(new java.awt.Color(171, 171, 171));
        BGroup2.add(loginCashierRadioBtn);
        loginCashierRadioBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loginCashierRadioBtn.setForeground(new java.awt.Color(25, 25, 25));
        loginCashierRadioBtn.setText("Cashier");

        signUpBtn.setBackground(new java.awt.Color(189, 3, 2));
        signUpBtn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn.setText("Sign Up");
        signUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        signUpLoginLbl.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        signUpLoginLbl.setForeground(new java.awt.Color(25, 25, 25));
        signUpLoginLbl.setText("Log In");
        signUpLoginLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLoginLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLoginLblMouseClicked(evt);
            }
        });

        signUpHaveAccLbl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        signUpHaveAccLbl.setForeground(new java.awt.Color(25, 25, 25));
        signUpHaveAccLbl.setText("Already have an account?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signUpRegisterLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signUpUsernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signUpPasswordLbl)
                            .addComponent(signUpPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signUpConfirmPasswordLbl)
                            .addComponent(signUpConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signInKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signUpUsernameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(loginAdminRadioBtn)
                                        .addGap(38, 38, 38)
                                        .addComponent(loginCashierRadioBtn)))))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(signUpHaveAccLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signUpLoginLbl)
                        .addGap(88, 88, 88))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(signUpRegisterLbl)
                .addGap(23, 23, 23)
                .addComponent(signUpUsernameLbl)
                .addGap(8, 8, 8)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(signUpPasswordLbl)
                .addGap(8, 8, 8)
                .addComponent(signUpPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(signUpConfirmPasswordLbl)
                .addGap(8, 8, 8)
                .addComponent(signUpConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(signInKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signUpUsernameLbl1))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginAdminRadioBtn)
                    .addComponent(loginCashierRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(signUpBtn)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpLoginLbl)
                    .addComponent(signUpHaveAccLbl))
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 380, 590));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/logo white.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Momentum");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/car.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventoryproject/bg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //sign up the user
    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        try{
            String userName = usernameTextField.getText();  //get all the data
            String password = String.valueOf(signUpPasswordTextField.getPassword());
            String confirmPassword = String.valueOf(signUpConfirmPasswordTextField.getPassword());
            String signInKey = String.copyValueOf(signInKeyTextField.getPassword());
            boolean successfull = true; //this will be the signal if the user has sign up successfully and will change the frame to login

            if(!userName.equals("") && !password.equals("") && !confirmPassword.equals("") && !signInKey.equals("")){ //if the textfields where not properly signed
                if(JOptionPane.showConfirmDialog(rootPane, "Continue?", "Confirmation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){ //cpnfirmation
                    if(password.equals(confirmPassword)){   //if the two input password matches
                        if(loginAdminRadioBtn.isSelected()) //if the admin position is selected
                            successfull = new AccountManagerProcess().addAccount(userName, password, signInKey, false); //add the accounts
                        else if(loginCashierRadioBtn.isSelected())  //otherwise
                            successfull = new AccountManagerProcess().addAccount(userName, password, signInKey, true);

                        if(successfull){    //if the user has successfully signed up
                            dispose();  //go to the login frame
                            Login logIn = new Login();
                            logIn.setVisible(true);
                        }
                    }
                    else
                        JOptionPane.showMessageDialog(rootPane, "Password and Password Confirmation Mismatched!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Please fillup the following!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Wrong Username or Password Input!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signUpBtnActionPerformed

    //go to login frame
    private void signUpLoginLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLoginLblMouseClicked
        dispose();
        Login logIn = new Login();
        logIn.setVisible(true);
    }//GEN-LAST:event_signUpLoginLblMouseClicked
    //for centering the the window
    private void centerWindow(Window w)
    {
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    setLocation((d.width-w.getWidth())/2,
    (d.height-w.getHeight())/2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton loginAdminRadioBtn;
    private javax.swing.JRadioButton loginCashierRadioBtn;
    private javax.swing.JPasswordField signInKeyTextField;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel signUpConfirmPasswordLbl;
    private javax.swing.JPasswordField signUpConfirmPasswordTextField;
    private javax.swing.JLabel signUpHaveAccLbl;
    private javax.swing.JLabel signUpLoginLbl;
    private javax.swing.JLabel signUpPasswordLbl;
    private javax.swing.JPasswordField signUpPasswordTextField;
    private javax.swing.JLabel signUpRegisterLbl;
    private javax.swing.JLabel signUpUsernameLbl;
    private javax.swing.JLabel signUpUsernameLbl1;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
